### ISSUE TITLE
desc parameter

### ISSUE THREAD

**Issue by TiMauzi** [mdmould/tqdm_pathos#2]
Is there a plan of adding the `desc` parameter to `tqdm_pathos`? In standard `tqdm` it is usually helpful for producing more verbose outputs.

**Comment by mdmould** [comment]
Thanks for the suggestion! I've added a `tqdm_kwargs` optional argument to `map` and `starmap`, which passes any extra kwargs to the `tqdm` progress bar constructor. E.g., `map(func, iterable, tqdm_kwargs={'desc': 'pbar description'})`.
